project:
  type: book
  output-dir: docs

book:
  title: "Time and Space Progress Journal"
  repo-url: https://github.com/pjournal/gh-pages-quarto-template
  chapters:
    - index.qmd
    - assignment1.qmd
    - dataprepturkstat.qmd
    - eda.qmd
    - project_report.qmd
    - project_report_pdf.pdf
    - Presentation.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

